### PR TITLE
Revamp efi_well_known_* variable handling

### PR DESCRIPTION
**Pull request by nvinson**
The current implementation attempts to use the linker to create aliases for efi_well_known_guids and efi_well_known_names. It also tries to use the linker to generate the variables efi_well_known_guids_end and efi_well_known_names_end.

When building with clang, the generated linker result results in a broken libefivar.so that causes programs to segfault when linked against it.  This change does away with linker script hacker and instead introduces pointers to store the locations of efi_well_known_guids_end and efi_well_known_names_end.

Additionally, efi_well_known_guids and efi_well_known_names are now created as pointers that point to the beginning of their respective arrays.

Signed-off-by: Nicholas Vinson <nvinson234@gmail.com>
Fixes: #234

### CODE REVIEW

**Comment by tedbrandston** [comment]
For what it's worth: I ran into an issue trying to switch from 37 -> 38 where the latter would cause my application to fail with `error while loading shared libraries: libefivar.so.1: ELF load command address/offset not page-aligned`. This patch does appear to fix my issue, though I don't think I'm exercising the functionality this touches.

Happy to provide any additional info I can.

**Comment by henriquehbr** [comment]
Thanks a lot for your work on this @nvinson! i was having a similar problem while trying to build static `efivar` libraries, by compiling from your branch i managed to get rid of those errors

**Comment by nvinson** [comment]
@vathpela @frozencemetery  Could this PR be merged please? It's been in review for almost 3 months with no negative reviews.

**Comment by rahul-singh-sandhu** [comment]
Nice work @nvinson! RedHat, you should merge this.

**Review by frozencemetery — APPROVED** [review]

**Pull request merged**
